import { render, screen, within } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { expect, it } from "vitest"
import { blockedExecutive, EXECUTIVE_DISCLOSURE, MATCH_BOUNDARY, PRESENTATION_BOUNDARY, projectExecutiveSnapshot, QUESTION_BOUNDARY, THEME_BOUNDARY } from "@/lib/gaia/policy-evidence-executive"
import { executiveFixture } from "@/lib/gaia/policy-evidence-executive.test-support"
import { ExecutiveEvidenceLayout, ExecutiveSourceEvidence, ExecutiveTrustEvidence } from "./policy-evidence-executive"

function fixture(state: "findings" | "zero" | "absent" = "findings") {
  const f = executiveFixture(state)
  return { ...f, page: projectExecutiveSnapshot(f.snapshotBytes, f.identity, f.bytes, f.optional) }
}
it("places H before detailed proof, with permanent synthetic disclosure and no first-view machinery dump", () => {
  const f = fixture(), { container } = render(<ExecutiveEvidenceLayout page={f.page}><section aria-label="Detailed proof">Existing evidence remains</section></ExecutiveEvidenceLayout>)
  expect(container.firstElementChild).toBe(screen.getByRole("region", { name: "GAIA Trust Evidence Snapshot" }))
  expect(container.firstElementChild?.nextElementSibling).toBe(screen.getByRole("region", { name: "Detailed proof" }))
  const view = within(screen.getByRole("region", { name: "GAIA Trust Evidence Snapshot" }))
  expect(view.getByRole("heading", { level: 1, name: "GAIA Trust Evidence Snapshot" })).toBeVisible()
  expect(view.getByText("Policy Evidence Demonstration")).toBeVisible()
  expect(view.getByText(EXECUTIVE_DISCLOSURE)).toBeVisible()
  expect(view.getByText(EXECUTIVE_DISCLOSURE).closest("details")).toBeNull()
  expect(container.firstElementChild?.querySelector("pre, code")).toBeNull()
  expect(container.firstElementChild?.textContent).not.toMatch(/SHA-256|bytesBase64|JSON|[a-f0-9]{64}/)
  expect(view.getByText(PRESENTATION_BOUNDARY)).toBeVisible()
})
it("orients with computed count, exact interpretation, separate human review and potential dissent", () => {
  const f = fixture()
  render(<ExecutiveTrustEvidence page={f.page} />)
  const interpretation = within(screen.getByRole("region", { name: "Executive interpretation" }))
  expect(interpretation.getByText("20")).toBeVisible()
  expect(interpretation.getByText(f.snapshot.modelInterpreted.originalMachineWording)).toBeVisible()
  expect(interpretation.getByText("MODEL-INTERPRETED · CAND-001")).toBeVisible()
  expect(interpretation.getByRole("link", { name: "Why This Insight?" })).toHaveAttribute("href", "#decision-evidence-brief")
  const review = within(screen.getByRole("region", { name: "Executive human review" }))
  expect(review.getByText("HUMAN-REVIEWED")).toBeVisible()
  expect(review.getByText("CONFIRM")).toBeVisible()
  expect(review.getByText(f.snapshot.humanReview.scope)).toBeVisible()
  const dissent = within(screen.getByRole("region", { name: "Executive frozen dissent" }))
  expect(dissent.getByText("POTENTIAL_UNSEEN_DISSENT · SYN-0001")).toBeVisible()
  expect(dissent.getByText("1 potential unseen dissent item")).toBeVisible()
  expect(dissent.getByText(f.snapshot.unseenDissent.challenge!.findings[0].quote)).toBeVisible()
})
it("orients beneath the exact interpretation with six stored themes while retaining the full disclosures", () => {
  const f = fixture()
  render(<ExecutiveTrustEvidence page={f.page} />)
  const interpretation = screen.getByRole("region", { name: "Executive interpretation" })
  expect(within(interpretation).getByRole("heading", { name: "What GAIA currently sees in the evidence" })).toBeVisible()
  expect(within(interpretation).getByText(f.snapshot.modelInterpreted.originalMachineWording)).toBeVisible()
  const context = within(interpretation).getByRole("region", { name: "What people are talking about" })
  expect(within(interpretation).getByRole("link", { name: "Why This Insight?" }).nextElementSibling).toBe(context)
  expect(Array.from(context.querySelectorAll("dl > div")).map((row) => [row.querySelector("dt")?.textContent, row.querySelector("dd")?.textContent])).toEqual([
    ["access-to-services", "4"], ["workforce-capability", "4"], ["data-governance", "4"],
    ["accountability", "3"], ["procurement-and-reuse", "3"], ["environmental-cost", "2"],
  ])
  expect(within(context).getByText("20 synthetic responses across six stored source themes. Theme frequency does not establish importance or consensus.")).toBeVisible()
  expect(context.querySelector("details")).toBeNull()
  const full = screen.getByRole("region", { name: "Executive source themes" })
  expect(context.compareDocumentPosition(full) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  expect(full.querySelectorAll("details")).toHaveLength(6)
})
it("links exact theme source IDs to inspectable complete source metadata and testimony below H", async () => {
  const f = fixture()
  render(<><ExecutiveTrustEvidence page={f.page} /><ExecutiveSourceEvidence page={f.page} /></>)
  expect(screen.getByText(THEME_BOUNDARY)).toBeVisible()
  const themes = within(screen.getByRole("region", { name: "Executive source themes" }))
  expect(themes.getByText("access-to-services")).toBeVisible()
  await userEvent.click(themes.getByText("access-to-services"))
  expect(themes.getByRole("link", { name: "SYN-0004" })).toHaveAttribute("href", "#executive-source-SYN-0004")
  const evidence = within(screen.getByRole("region", { name: "Executive theme source evidence" }))
  await userEvent.click(evidence.getByText("SYN-0004 · access-to-services"))
  expect(evidence.getByText(f.page.core.sources[3].text)).toBeVisible()
  expect(document.getElementById("executive-source-SYN-0004")?.tagName).toBe("SUMMARY")
})
it("retains exact adjacent zero statements and never treats absent dissent as zero", () => {
  const { rerender } = render(<ExecutiveTrustEvidence page={fixture("zero").page} />)
  const dissent = within(screen.getByRole("region", { name: "Executive frozen dissent" }))
  expect(dissent.getByText("No potential unseen dissent was surfaced by this challenge run.").nextElementSibling?.textContent).toBe("This does not establish that no dissent exists.")
  rerender(<ExecutiveTrustEvidence page={fixture("absent").page} />)
  expect(dissent.getByText("ABSENT")).toBeVisible()
  expect(dissent.getByText("Challenge evidence absent; no finding count established.")).toBeVisible()
  expect(dissent.queryByText("0 potential unseen dissent items")).not.toBeInTheDocument()
  expect(dissent.queryByText("No potential unseen dissent was surfaced by this challenge run.")).not.toBeInTheDocument()
})
it("keeps limitations visible, questions labelled, and associated F/G states bounded with native anchors", () => {
  const f = fixture()
  render(<ExecutiveTrustEvidence page={f.page} />)
  for (const limit of f.page.core.limitations) expect(screen.getByText(limit.text)).toBeVisible()
  expect(screen.getByRole("heading", { name: "Questions leadership should examine" })).toBeVisible()
  expect(screen.getByText(QUESTION_BOUNDARY)).toBeVisible()
  expect(screen.getByText("RECORDED")).toBeVisible()
  expect(screen.getByText("RECORDED_EVIDENCE_MATCHES_CURRENT")).toBeVisible()
  expect(screen.getByText("GAIA did not make, recommend, approve or validate the decision.")).toBeVisible()
  expect(screen.getByText(MATCH_BOUNDARY)).toBeVisible()
  expect(screen.getByRole("link", { name: "Inspect Human Decision Record" })).toHaveAttribute("href", "#human-decision-title")
  expect(screen.getByRole("link", { name: "Has the Evidence Changed?" })).toHaveAttribute("href", "#decision-evidence-change")
  expect(screen.queryByRole("button")).not.toBeInTheDocument()
  expect(screen.queryByRole("textbox")).not.toBeInTheDocument()
})
it("shows PARTIAL for missing F/G while preserving valid core and avoiding fabricated status", () => {
  const f = fixture(), partial = projectExecutiveSnapshot(f.snapshotBytes, f.identity, f.bytes)
  render(<ExecutiveTrustEvidence page={partial} />)
  expect(screen.getByText("Presentation: PARTIAL.")).toBeVisible()
  expect(screen.getByText(f.snapshot.modelInterpreted.originalMachineWording)).toBeVisible()
  expect(screen.queryByText("RECORDED")).not.toBeInTheDocument()
  expect(screen.queryByText("RECORDED_EVIDENCE_MATCHES_CURRENT")).not.toBeInTheDocument()
  expect(screen.getAllByText("UNAVAILABLE")).toHaveLength(2)
})
it("shows BLOCKED without zero findings or inferred interpretation but retains the proof link", () => {
  render(<ExecutiveTrustEvidence page={blockedExecutive("Invalid or unavailable selected evidence, including dissent, blocks this view.")} />)
  expect(screen.getByText("Presentation: BLOCKED.")).toBeVisible()
  expect(screen.getByRole("alert")).toHaveTextContent("including dissent")
  expect(screen.getByText(EXECUTIVE_DISCLOSURE)).toBeVisible()
  expect(screen.queryByRole("region", { name: "Executive interpretation" })).not.toBeInTheDocument()
  expect(screen.queryByText("No potential unseen dissent was surfaced by this challenge run.")).not.toBeInTheDocument()
  expect(screen.getByRole("link", { name: "Inspect the detailed policy evidence" })).toHaveAttribute("href", "#policy-evidence-detail")
})
